-- database exploration -> when we first get the database access it is high time to analyze what structure of our database is like tables, views, columns,stored procedures etc.

-- explore all objects of the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- explore all the columns in the databases's tables
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';


-- dimensions exploration -> identifying all the unique values (or categories) in each dimensions mainly used for the dimensions based data categorical columns

-- explore all the countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers


-- explore all the categories or all the categorical columns " the major divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1, 2, 3

-- EXEC sp_helptext 'gold.dim_customers';


-- date explorations -> identify the eraliest and latest dates( boundaries ) . 

-- find the very first as well as the very last or the most recent order date
-- how many years of sales data is available for the organisation
SELECT
MIN(order_date) AS first_order_date, 
MAX(order_date) AS recent_order_date ,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- find the youngest as well as the oldest customers
SELECT
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers


-- measures exploration -> refers to calculating and finding out the key metric of the businesses from the big numbers to draw the businesses insights
-- aggregate functions are majorily used here


-- find the total sales 
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales
-- find total how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales
-- find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales
-- find the total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
-- find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products
-- find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers
-- find the total number of customers that has actually placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.dim_customers

-- generic number to showcase all the big numbers from the business organisation
SELECT 'total sales' AS measure_name, SUM(sales_amount) AS total_sales FROM gold.fact_sales
UNION ALL
SELECT 'total quantity',  SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'average price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'total no. orders' , COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'total no. products' , COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'total no. customers' , COUNT(DISTINCT customer_key) FROM gold.dim_customers

-- magnitude analysis 
-- compare the measure values by categories or dimensions which ultimately helps us understand the category based importance in the table


-- find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY  country
ORDER BY total_customers DESC
-- find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY  gender
ORDER BY total_customers DESC
-- find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY  category
ORDER BY total_products DESC
-- what is the average costs in each category
SELECT 
category,
AVG(cost) AS average_costs
FROM gold.dim_products
GROUP BY  category
ORDER BY average_costs DESC
-- what is the total revenue generated for each category
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
-- find the total revenue that is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC
-- what is the distribution of sold items accross countries
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC




-- ranking analysis
-- ranking or ordering the values of various dimensions or the various categories by their respective measures to identify or detect the top performers and the relatively lower one performers

-- which 5/five products generate the highest revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

SELECT TOP 5
p.subcategory,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

SELECT * FROM(
	SELECT 
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER ( ORDER BY SUM(f.sales_amount) DESC ) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name)t
WHERE rank_products <= 5
-- what are the 5/five worst - performing products in terms of sales
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC
-- find the top 10/ten customers who have generated the hg=ighest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC
-- find the 3/three customers with the fewest orders placed
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders_placed
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders_placed ASC










































